-- =============================================================================
-- DEPRECATED: superseded by supabase-schema.sql (single full schema).
-- Run supabase-schema.sql in the Supabase SQL Editor instead.
-- This file is kept only for reference / old deployment notes.
-- =============================================================================
